project:
  title: "WBI STEM"
  output-dir: ../docs
  type: website


format:
  html:
    code-fold: true
    html-math-method: katex

  revealjs:
    theme: [default, evelyn.scss]
    css: evelyn.css
    logo: 'img/DDT_Logo_wo_Bk.png'
    footer: "Magnetic Anomaly Mapping: STEM Activity"
    scrollable: true
    transition: slide
    transition-speed: fast
    chalkboard:
      buttons: true

execute:
  echo: true
  output: true
  error: true

jupyter: python3

